---
jobs:
  build-push:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - id: 'metadata'
      uses: 'docker/metadata-action@v5'
      with:
        images: 'econialabs/emojicoin-broker'
        tags: |
          type=ref,event=branch
          type=match,pattern=indexer-v(.*),group=1
    - uses: 'docker/setup-qemu-action@v3'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/login-action@v3'
      with:
        password: '${{ secrets.DOCKERHUB_TOKEN }}'
        username: '${{ secrets.DOCKERHUB_USERNAME }}'
    - uses: 'docker/build-push-action@v6'
      with:
        cache-from: 'type=gha'
        cache-to: 'type=gha,mode=max'
        context: 'src/indexer'
        file: 'src/indexer/broker/Dockerfile'
        labels: '${{ steps.metadata.outputs.labels }}'
        platforms: '${{ vars.DOCKER_IMAGE_PLATFORMS }}'
        push: 'true'
        tags: '${{ steps.metadata.outputs.tags }}'
name: 'Build broker Docker image and push to Docker Hub'
'on':
  push:
    branches:
      - 'unstable'
    tags:
      - 'indexer-v*'
...
